// SPDX-License-Identifier: MIT

import { Palette as StdPalette } from "std-widgets.slint";
import { AppState } from "../../appState.slint";
import { LightsTheme } from "lightsTheme.slint";
import { LightsSidebar } from "sidebar.slint";
import { HeroLightCard } from "heroLightCard.slint";
import { RoomCard } from "roomCard.slint";
import { ShadowText } from "shadowText.slint";

export component LightsScreen inherits Rectangle {
    in-out property <float> brightness: 82;

    width: 100%;
    height: 100%;
    background: LightsTheme.background;

    init => {
        AppState.window-width = root.width;
        AppState.window-height = root.height;
        StdPalette.color-scheme = ColorScheme.dark;
    }

    changed width => {
        AppState.window-width = root.width;
    }

    changed height => {
        AppState.window-height = root.height;
    }

    LightsSidebar {
        x: 22px;
        y: 28px;
        width: 104px;
        height: 568px;
    }

    ShadowText {
        x: 166px;
        y: 37px;
        width: 260px;
        height: 60px;
        label: "Lights";
        size: 51px;
        weight: FontWeight.bold;
    }

    ShadowText {
        x: 854px;
        y: 44px;
        width: 74px;
        height: 46px;
        label: "3:12";
        size: 39px;
        weight: FontWeight.normal;
        text-color: #c9bde4;
    }

    HeroLightCard {
        x: 158px;
        y: 106px;
        width: 780px;
        height: 289px;
        brightness <=> root.brightness;
    }

    RoomCard {
        x: 158px;
        y: 416px;
        width: 375px;
        height: 181px;
        room-name: "Back Porch";
        state-label: "70%";
        active: true;
    }

    RoomCard {
        x: 548px;
        y: 416px;
        width: 390px;
        height: 181px;
        room-name: "Yard";
        state-label: "Off";
    }
}
