# Copyright © SixtyFPS GmbH <info@slint.dev>
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

[package]
name = "i-slint-backend-vnc"
description = "VNC backend for Slint"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "lib.rs"

[features]
default = []

[dependencies]
i-slint-core = { workspace = true, features = ["std"] }
i-slint-common = { workspace = true }
i-slint-renderer-software = { workspace = true, features = ["std"] }
tokio = { version = "1", features = ["rt", "net", "sync", "time", "macros", "io-util"] }
bytemuck = { workspace = true }
log = { workspace = true }

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]
